name: Triggered by Source Repo

on:
  repository_dispatch:
    types:
      - trigger_workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run your tasks
        run: |
          echo "Triggered by source repository!"
          # Add your actual tasks here
